name: shamchiroq
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  mask_text_input_formatter: ^2.3.0
  provider: ^6.0.2
  audioplayers: ^0.20.1
  http: ^0.13.4
  shared_preferences: ^2.0.13
  camera: ^0.9.5
  file_picker: ^4.5.1
  path: ^1.8.0
  native_pdf_view: ^6.0.0+1
  pdf_text: ^0.5.0
  flutter_tesseract_ocr: ^0.4.20
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  just_audio: ^0.9.28
  advance_pdf_viewer: ^2.0.1
  pdf_viewer_plugin: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/tessdata/
